sudo: required
services:
  - docker

before_install:
  - docker build -t mune/docker-go-trading .

script:
  - docker run -e CI=true mune/docker-go-trading go test ./...

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-go-trading"
#  env: "DockerGoTrading-env"
#  bucket_name: "elasticbeanstalk-us-east-2-045184984172"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY